### ISSUE TITLE
Display game rules

### ISSUE THREAD

**Issue by HamdaanAliQuatil** [GDSC-IIIT-Kalyani/react-star-match#2]
- [ ] Update readme.md to display rules in a separate section.

**Comment by bharat-chotwani** [comment]
What are the game rules and are the rules specific?

**Comment by HamdaanAliQuatil** [comment]
Hey @BharatChotwani. A detailed rule set is now displayed before the game starts. Check at https://react-star-match.herokuapp.com/

**Comment by vishuuwu** [comment]
Please assign this issue to me.
